Repository webserv-80000coding-jiphyeonjeon/webserv, pull requests merged in 2022-08, with the labels that each got.

#7 Configuration file parsing 구현
  .clang-format
  .gitignore
  Makefile
  config/default.conf
  config/test.conf
  include/Config.hpp
  include/ConfigCommon.hpp
  include/ConfigLocation.hpp
  include/ConfigServer.hpp
  include/Parser.hpp
  include/Scanner.hpp
  include/color.hpp
  src/Config.cpp
  src/ConfigCommon.cpp
  src/ConfigLocation.cpp
  src/ConfigServer.cpp
  src/Parser.cpp
  src/Scanner.cpp
  src/main.cpp
  www/50x.html
  www/index.html
Labels: Feature :star2:

#8 파싱된 결과 기준 server setting 구현
  Makefile
  include/Config.hpp
  include/Server.hpp
  include/Webserv.hpp
  src/Config.cpp
  src/Server.cpp
  src/Webserv.cpp
  src/main.cpp
Labels: Feature :star2:

#9 select() 활용한 multiplexing server틀 구현
  Makefile
  include/Server.hpp
  include/Webserv.hpp
  src/Client.cpp
  src/Parser.cpp
  src/Server.cpp
  src/Webserv.cpp
  src/main.cpp
Labels: Feature :star2:

#12 Parser 리팩토링 및 Log class 추가
  Makefile
  config/default.conf
  include/Log.hpp
  include/Parser.hpp
  src/Config.cpp
  src/Log.cpp
  src/Parser.cpp
  src/Scanner.cpp
  src/Webserv.cpp
  src/main.cpp
Labels: Feature :star2:, Refactor :recycle:

#15 HTTP request parsing 구현 #4
  .gitignore
  include/Processor.hpp
  include/Request.hpp
  include/Utilities.hpp
  src/Processor.cpp
  src/Request.cpp
  src/Utilities.cpp
  src/main.cpp
Labels: Feature :star2:

#17 File class 최초 구현
  include/File.hpp
  src/File.cpp
Labels: Feature :star2:

#19 Server - Processor 연동 및 HTTP Request 파트 리팩토링
  .gitignore
  Makefile
  include/Processor.hpp
  include/Request.hpp
  include/Server.hpp
  include/Utilities.hpp
  include/Webserv.hpp
  src/Processor.cpp
  src/Request.cpp
  src/Server.cpp
  src/Utilities.cpp
  src/Webserv.cpp
  src/main.cpp
Labels: Feature :star2:, Refactor :recycle:

#22 Processor에 필요한 ConfigServer 전달
  include/Config.hpp
  include/Processor.hpp
  include/Server.hpp
  include/Webserv.hpp
  src/Config.cpp
  src/Processor.cpp
  src/Server.cpp
  src/Webserv.cpp
Labels: Feature :star2:

#23 conf 파일 directive 추가
  config/test.conf
  include/Config.hpp
  include/ConfigCommon.hpp
  include/ConfigLocation.hpp
  include/ConfigServer.hpp
  include/Parser.hpp
  src/Config.cpp
  src/ConfigCommon.cpp
  src/ConfigLocation.cpp
  src/ConfigServer.cpp
  src/Parser.cpp
Labels: Feature :star2:

#25 Processor에 필요한 ConfigServer 전달 방식 수정
  config/find_server.conf
  include/Config.hpp
  include/ConfigServer.hpp
  include/Processor.hpp
  include/Request.hpp
  include/Server.hpp
  include/Utilities.hpp
  include/Webserv.hpp
  src/Config.cpp
  src/ConfigServer.cpp
  src/Parser.cpp
  src/Processor.cpp
  src/Request.cpp
  src/Server.cpp
  src/Utilities.cpp
  src/Webserv.cpp
  src/main.cpp
Labels: Feature :star2:

#27 GET, POST, DELETE 최소 동작 및 Response 클래스 구현
  Makefile
  include/File.hpp
  include/Processor.hpp
  include/Response.hpp
  include/Utilities.hpp
  src/File.cpp
  src/Processor.cpp
  src/Response.cpp
  src/Server.cpp
  src/Webserv.cpp
Labels: Feature :star2:

#29 HTTP Request 파싱 중 발생한 exception 처리
  include/Processor.hpp
  include/Response.hpp
  include/Server.hpp
  src/Processor.cpp
  src/Request.cpp
  src/Response.cpp
  src/Server.cpp
  src/Webserv.cpp
Labels: Bug :bug:

#35 HTTP 메서드 입출력 방식 변경(write/read -> file stream)
  Makefile
  include/FileManager.hpp
  include/Processor.hpp
  src/File.cpp
  src/FileManager.cpp
  src/Processor.cpp
Labels: Bug :bug:

#44 HTTP Method 구현
  config/test.conf
  include/FileManager.hpp
  include/Processor.hpp
  include/Utilities.hpp
  src/FileManager.cpp
  src/Processor.cpp
  src/Request.cpp
  src/Response.cpp
  src/Server.cpp
  src/Utilities.cpp
  src/Webserv.cpp
  www/image.jpeg
  www/um.gif
Labels: Feature :star2:

#45 partial send 기능 구현
  Makefile
  include/Processor.hpp
  include/Server.hpp
  src/Processor.cpp
  src/Server.cpp
  src/Webserv.cpp
Labels: Feature :star2:

#47 CGI handler 구현
  Makefile
  include/CgiHandler.hpp
  include/ConfigCommon.hpp
  include/Processor.hpp
  include/Response.hpp
  include/Webserv.hpp
  src/CgiHandler.cpp
  src/FileManager.cpp
  src/Processor.cpp
  src/Request.cpp
  src/Response.cpp
  src/Server.cpp
Labels: Feature :star2:

#48 AutoIndexing 구현 및 config 인자 처리
  config/default.conf
  include/ConfigCommon.hpp
  include/ConfigLocation.hpp
  include/FileManager.hpp
  include/Processor.hpp
  src/ConfigCommon.cpp
  src/ConfigLocation.cpp
  src/FileManager.cpp
  src/Parser.cpp
  src/Processor.cpp
  src/Request.cpp
  www/favicon.ico
  www/index.html
Labels: Feature :star2:

#53 Request timeout 로직 & MIME 구분 추가
  .gitignore
  include/Processor.hpp
  include/Request.hpp
  include/Server.hpp
  include/Utilities.hpp
  include/Webserv.hpp
  src/FileManager.cpp
  src/Processor.cpp
  src/Request.cpp
  src/Server.cpp
  src/Utilities.cpp
  src/Webserv.cpp
Labels: Bug :bug:, Feature :star2:

#54 평가를 위한 세팅 및 쉘 스크립트 작성 (+소소한 수정)
  8jip_test.sh
  Makefile
  config/default.conf
  include/Utilities.hpp
  src/Processor.cpp
  src/Request.cpp
  src/Server.cpp
  src/Utilities.cpp
  src/Webserv.cpp
  www/404.html
  www/42jiphyeonjeon/books/Clean_Code
  www/42jiphyeonjeon/books/Code_Complete_2
  www/42jiphyeonjeon/books/Game_Engine_Architecture
  www/42jiphyeonjeon/books/Head_First_Design_Patterns
  www/42jiphyeonjeon/books/Introduction_to_Algorithms
  www/42jiphyeonjeon/books/Introduction_to_Computer_Science_Using_Python
  www/42jiphyeonjeon/books/Operating_System_Concepts_9th_Edition
  www/42jiphyeonjeon/books/The_C++_Programming_Language
  www/42jiphyeonjeon/index.html
  www/42jiphyeonjeon/logo.png
  www/50x.html
  www/80000coding/index.html
  www/80000coding/logo.jpg
Labels: Bug :bug:, docs :memo:, Feature :star2:
